export const CarsListData = [
  {
    id: 1,
    brand: "Toyota",
    name: "Corolla",
    model: 2022,
    price: 25000,
    distance: 15000,
    registration: 2024,
    type: "Sedan",
    color: "Silver",
    fuel: "Petrol",
    gear: "Automatic",
  },
  {
    id: 2,
    brand: "Honda",
    name: "Civic",
    model: 2021,
    price: 27000,
    distance: 18000,
    registration: 2024,
    type: "Sedan",
    color: "Black",
    fuel: "Petrol",
    gear: "Manual",
  },
  {
    id: 3,
    brand: "BMW",
    name: "X5",
    model: 2020,
    price: 60000,
    distance: 20000,
    registration: 2024,
    type: "SUV",
    color: "White",
    fuel: "Diesel",
    gear: "Automatic",
  },
  // Add more cars below
  {
    id: 4,
    brand: "Ford",
    name: "Mustang",
    model: 2023,
    price: 45000,
    distance: 10000,
    registration: 2022,
    type: "Sports Car",
    color: "Red",
    fuel: "Petrol",
    gear: "Manual",
  },
  {
    id: 5,
    brand: "Chevrolet",
    name: "Camaro",
    model: 2022,
    price: 50000,
    distance: 8000,
    registration: 2023,
    type: "Sports Car",
    color: "Yellow",
    fuel: "Petrol",
    gear: "Automatic",
  },
  {
    id: 6,
    brand: "Audi",
    name: "A4",
    model: 2021,
    price: 35000,
    distance: 12000,
    registration: 2022,
    type: "Sedan",
    color: "Blue",
    fuel: "Diesel",
    gear: "Automatic",
  },
  {
    id: 7,
    brand: "Mercedes-Benz",
    name: "GLE",
    model: 2023,
    price: 70000,
    distance: 15000,
    registration: 2023,
    type: "SUV",
    color: "Black",
    fuel: "Petrol",
    gear: "Automatic",
  },
  {
    id: 8,
    brand: "Lamborghini",
    name: "Huracan",
    model: 2024,
    price: 300000,
    distance: 5000,
    registration: 2023,
    type: "Sports Car",
    color: "Orange",
    fuel: "Petrol",
    gear: "Automatic",
  },
  {
    id: 9,
    brand: "Porsche",
    name: "911",
    model: 2023,
    price: 180000,
    distance: 7000,
    registration: 2023,
    type: "Sports Car",
    color: "Silver",
    fuel: "Petrol",
    gear: "Automatic",
  },
  {
    id: 10,
    brand: "Tesla",
    name: "Model S",
    model: 2022,
    price: 80000,
    distance: 10000,
    registration: 2023,
    type: "Electric",
    color: "White",
    fuel: "Electricity",
    gear: "Automatic",
  },
];
